apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jp3lnf9cy-nodejs 
  janus-idp.io/tekton: jp3lnf9cy-nodejs
  backstage.io/kubernetes-id: jp3lnf9cy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jp3lnf9cy-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml