apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jp3lnf9cy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jp3lnf9cy-nodejs 
  name: jp3lnf9cy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jp3lnf9cy-nodejs 
